name: translator-management-system

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - ./data/.env
    environment:
      DB_URL: sqlite:////data/app.db
    volumes:
      - ./data:/data
